export const MASTER = [
    { path: "https://estiloconsalud.com/con-2-ingrediente-hice-un-remedio-que-acabo-con-10-anos-de-diabetes-en-solo-5-dias-dile-adios/",
      type: "iframe",
      source_name: "Eliminar diabetes con dos ingredientes",
      source_url: "https://estiloconsalud.com/con-2-ingrediente-hice-un-remedio-que-acabo-con-10-anos-de-diabetes-en-solo-5-dias-dile-adios/",
      secure: false,
      true_or_false: false,
      score: 20,
      feedback_path: "http://saludsinbulos.com/alertas/diabetes-dos-ingredientes/",
      feedback_search: "https://www.google.es/search?q=diabetes+dos+ingredientes+bulo",
      feedback_sitename: "saludsinbulos"
    },
    { path: "./assets/images/quiz/phishing02.png",
      source_name: "Olivia Pareja, venta zapatos",
      source_url: "http://www.oliviapareja.es/",
      secure: false,
      true_or_false: false,
      score: 10,
      feedback_path: "./assets/images/quiz/phishing02_feedback.png",
      feedback_text: ""
    },
    { path: "./assets/images/quiz/phishing01.png",
      source_name: "Banco Santander",
      source_url: "http://www.bitidlma.com/s4nbnc/San/Home.php?i=tablet.bancosantander.es/supernetLogin/indexSan.html?tsid=20182140546#!login",
      secure: false,
      true_or_false: false,
      score: 10,
      feedback_path: "./assets/images/quiz/phishing01_feedback.png",
      feedback_text: ""
    },
    { path: "./assets/images/quiz/phishing05.png",
      source_name: "Movistar",
      source_url: "http://www.thescreenroomstore.com/phonemoviees/",
      secure: false,
      true_or_false: false,
      score: 10,
      feedback_path: "./assets/images/quiz/phishing05_feedback.png",
      feedback_text: ""
    },
    { path: "./assets/images/quiz/noticia1.png",
      source_name: "ABC",
      source_url: "www.abc.es/espana/catalunya/abci-exconsejera-ponsati-cuestiona-junqueras-desde-bruselas-y-apuesta-nuevas-elecciones-antes-pedir-perdon-201802031649_noticia.html",
      secure: true,
      true_or_false: true,
      score: 5,
      feedback_path: "./assets/images/quiz/noticia1s.png",
      feedback_text: "La noticia es verdadera, viene de un medio nacional, el periódico ABC.",
      with_margins: true
    },
    { path: "./assets/images/quiz/noticia2.png",
      source_name: "ABC",
      source_url: "www.abc.es/economia/abci-draghi-principal-obstaculo-para-guindos-201802030215_noticia.html",
      secure: true,
      true_or_false: true,
      score: 5,
      feedback_path: "./assets/images/quiz/noticia2s.png",
      feedback_text: " La noticia es verdadera.",
      with_margins: true
    },
    { path: "./assets/images/quiz/noticia3.png",
      source_name: "Veterinarios.info",
      source_url: "http://www.veterinarios.info/2797/espana-crea-un-cuerpo-de-policia-que-velara-por-los-derechos-de-los-animales-compartelo/",
      secure: false,
      true_or_false: false,
      score: 15,
      feedback_path: "./assets/images/quiz/noticia3s.png",
      feedback_text: "La noticia es falsa. Hay que fijarse que es un blog y conviene contrastar la información, además anima a difundirlo, que siempre lleva a la sospecha. Una rápida búsqueda en Google y verás que es falsa.",
      with_margins: true
    },
]



export const PHISHING = [
    { path: "./assets/images/quiz/phishing01.png",
      source_name: "Banco Santander",
      source_url: "http://www.bitidlma.com/s4nbnc/San/Home.php?i=tablet.bancosantander.es/supernetLogin/indexSan.html?tsid=20182140546#!login",
      secure: false,
      true_or_false: false,
      score: 10,
      feedback_path: "./assets/images/quiz/phishing01_feedback.png",
      feedback_text: "",
    },
    { path: "./assets/images/quiz/phishing02.png",
      source_name: "Olivia Pareja, venta zapatos",
      source_url: "http://www.oliviapareja.es/",
      secure: false,
      true_or_false: false,
      score: 10,
      feedback_path: "./assets/images/quiz/phishing02_feedback.png",
      feedback_text: "",
    },
    { path: "./assets/images/quiz/phishing03.png",
      source_name: "Banco ING Direct",
      source_url: "ing.ingdirect.es/pfm/#login/credentials",
      secure: true,
      true_or_false: true,
      score: 10,
      feedback_path: "./assets/images/quiz/phishing03_feedback.png",
      feedback_text: "",
    },
    { path: "./assets/images/quiz/phishing04.png",
      source_name: "UGG venta zapatos",
      source_url: "http://uggvipmall.com/",
      secure: false,
      true_or_false: false,
      score: 10,
      feedback_path: "./assets/images/quiz/phishing04_feedback.png",
      feedback_text: "",
    },
    { path: "./assets/images/quiz/phishing05.png",
      source_name: "Movistar",
      source_url: "http://www.thescreenroomstore.com/phonemoviees/",
      secure: false,
      true_or_false: false,
      score: 10,
      feedback_path: "./assets/images/quiz/phishing05_feedback.png",
      feedback_text: "",
    },
    { path: "./assets/images/quiz/phishing06.png",
      source_name: "Netflix registro",
      source_url: "www.netflix.com/signup/regform",
      feedback_text: "",
      secure: true,
      true_or_false: true,
      score: 10,
      feedback_path: "./assets/images/quiz/phishing06_feedback.png",
    },
    { path: "./assets/images/quiz/phishing07.png",
      source_name: "Banco BBVA",
      source_url: "217.61.97.40/bbva-es/login.php?connexion=581064859121-795980693947419044042968889935&error=false&login=9651423418138&attempt=581064859121-795980693947419044042968889935&error=false&login=9651423418138",
      secure: false,
      true_or_false: false,
      score: 10,
      feedback_path: "./assets/images/quiz/phishing07_feedback.png",
      feedback_text: "",
    },
    { path: "./assets/images/quiz/phishing08.png",
      source_name: "Pandora, venta joyería",
      source_url: "http://www.ptoshmarks.com/index/",
      secure: false,
      true_or_false: false,
      score: 10,
      feedback_path: "./assets/images/quiz/phishing08_feedback.png",
      feedback_text: "",
    },
    { path: "./assets/images/quiz/phishing09.png",
      source_name: "Tuenti movil, contratar",
      source_url: "www.tuenti.es/checkout/?uuid=Septiembre_2017_D10_1_Postpay",
      secure: true,
      true_or_false: true,
      score: 10,
      feedback_path: "./assets/images/quiz/phishing09_feedback.png",
      feedback_text: "",
    },
    { path: "./assets/images/quiz/phishing10.png",
      source_name: "Recompensas Google",
      source_url: "http://iw0gdtkm.uqsq.online/?sov=786337448&hid=bpjtptnhbddf&ref=dm&&noalert=1&cntrl=00100&pid=555&redid=491&gsid=68&campaign_id=42&p_id=555&id=XNSX.6225%3A%3A4516%3A%3A%3A%3A%3A%3A92.177.180.46-r491-t68&impid=6e310904-2837-11e8-86a3-4e4e3e1c4387",
      secure: false,
      true_or_false: false,
      score: 10,
      feedback_path: "./assets/images/quiz/phishing10_feedback.png",
      feedback_text: "",
    },
]

export const SALUD = [
    { path: "https://estiloconsalud.com/con-2-ingrediente-hice-un-remedio-que-acabo-con-10-anos-de-diabetes-en-solo-5-dias-dile-adios/",
      type: "iframe",
      source_name: "Eliminar diabetes con dos ingredientes",
      source_url: "https://estiloconsalud.com/con-2-ingrediente-hice-un-remedio-que-acabo-con-10-anos-de-diabetes-en-solo-5-dias-dile-adios/",
      secure: true,
      true_or_false: false,
      score: 20,
      feedback_path: "http://saludsinbulos.com/alertas/diabetes-dos-ingredientes/",
      feedback_search: "https://www.google.es/search?q=diabetes+dos+ingredientes+bulo",
      feedback_sitename: "saludsinbulos"
    },
    { path: "https://estiloconsalud.com/con-2-ingrediente-hice-un-remedio-que-acabo-con-10-anos-de-diabetes-en-solo-5-dias-dile-adios/",
      type: "iframe",
      source_name: "Eliminar diabetes con dos ingredientes",
      source_url: "https://estiloconsalud.com/con-2-ingrediente-hice-un-remedio-que-acabo-con-10-anos-de-diabetes-en-solo-5-dias-dile-adios/",
      secure: false,
      true_or_false: false,
      score: 20,
      feedback_path: "http://saludsinbulos.com/alertas/diabetes-dos-ingredientes/",
      feedback_search: "https://www.google.es/search?q=diabetes+dos+ingredientes+bulo",
      feedback_sitename: "saludsinbulos"
    },
  ]
