export const QUESTIONS = [
    { path: "./assets/images/quiz/phishing01.png",
      source_name: "Banco Santander",
      source_url: "http://www.bitidlma.com/s4nbnc/San/Home.php?i=tablet.bancosantander.es/supernetLogin/indexSan.html?tsid=20182140546#!login",
      secure: false,
      true_or_false: false,
      score: 10,
      feedback_path: "./assets/images/quiz/phishing01_feedback.png",
      feedback_text: ""
    },
    { path: "./assets/images/quiz/phishing02.png",
      source_name: "Olivia Pareja, venta zapatos",
      source_url: "http://www.oliviapareja.es/",
      secure: false,
      true_or_false: false,
      score: 10,
      feedback_path: "./assets/images/quiz/phishing02_feedback.png",
      feedback_text: ""
    },
    { path: "./assets/images/quiz/phishing03.png",
      source_name: "Banco ING Direct",
      source_url: "ing.ingdirect.es/pfm/#login/credentials",
      secure: true,
      true_or_false: true,
      score: 10,
      feedback_path: "./assets/images/quiz/phishing03_feedback.png",
      feedback_text: ""
    },
    { path: "./assets/images/quiz/phishing04.png",
      source_name: "UGG venta zapatos",
      source_url: "http://uggvipmall.com/",
      secure: false,
      true_or_false: false,
      score: 10,
      feedback_path: "./assets/images/quiz/phishing04_feedback.png",
      feedback_text: ""
    },
    { path: "./assets/images/quiz/phishing05.png",
      source_name: "Movistar",
      source_url: "http://www.thescreenroomstore.com/phonemoviees/",
      secure: false,
      true_or_false: false,
      score: 10,
      feedback_path: "./assets/images/quiz/phishing05_feedback.png",
      feedback_text: ""
    },
    { path: "./assets/images/quiz/phishing06.png",
      source_name: "Netflix registro",
      source_url: "www.netflix.com/signup/regform",
      secure: true,
      true_or_false: true,
      score: 10,
      feedback_path: "./assets/images/quiz/phishing06_feedback.png",
      feedback_text: ""
    },
    { path: "./assets/images/quiz/phishing07.png",
      source_name: "Banco BBVA",
      source_url: "217.61.97.40/bbva-es/login.php?connexion=581064859121-795980693947419044042968889935&error=false&login=9651423418138&attempt=581064859121-795980693947419044042968889935&error=false&login=9651423418138",
      secure: false,
      true_or_false: false,
      score: 10,
      feedback_path: "./assets/images/quiz/phishing07_feedback.png",
      feedback_text: ""
    },
    { path: "./assets/images/quiz/phishing08.png",
      source_name: "Pandora, venta joyería",
      source_url: "http://www.ptoshmarks.com/index/",
      secure: false,
      true_or_false: false,
      score: 10,
      feedback_path: "./assets/images/quiz/phishing08_feedback.png",
      feedback_text: ""
    },
    { path: "./assets/images/quiz/phishing09.png",
      source_name: "Tuenti movil, contratar",
      source_url: "www.tuenti.es/checkout/?uuid=Septiembre_2017_D10_1_Postpay",
      secure: true,
      true_or_false: true,
      score: 10,
      feedback_path: "./assets/images/quiz/phishing09_feedback.png",
      feedback_text: ""
    },
    { path: "./assets/images/quiz/phishing10.png",
      source_name: "Recompensas Google",
      source_url: "http://iw0gdtkm.uqsq.online/?sov=786337448&hid=bpjtptnhbddf&ref=dm&&noalert=1&cntrl=00100&pid=555&redid=491&gsid=68&campaign_id=42&p_id=555&id=XNSX.6225%3A%3A4516%3A%3A%3A%3A%3A%3A92.177.180.46-r491-t68&impid=6e310904-2837-11e8-86a3-4e4e3e1c4387",
      secure: false,
      true_or_false: false,
      score: 10,
      feedback_path: "./assets/images/quiz/phishing10_feedback.png",
      feedback_text: ""
    },
]
